# generated by datamodel-codegen:
#   filename:  agent-step-request.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from . import agent_step_response_schema


class FieldSpec(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fieldId: str
    description: str
    expectedType: str | None = None


class HistoryEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    toolCall: agent_step_response_schema.AgentStepResponse
    observation: str | None


class AgentStepRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    goal: str
    fieldSpec: FieldSpec
    a11ySnapshot: str
    history: list[HistoryEntry]
