# generated by datamodel-codegen:
#   filename:  agent-step-response.schema.json

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class AgentStepResponseClick(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tool: Literal['click']
    ref: str


class AgentStepResponseType(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tool: Literal['type']
    ref: str
    text: str


class AgentStepResponsePress(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tool: Literal['press']
    ref: str
    key: str


class AgentStepResponseWaitFor(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tool: Literal['waitFor']
    refOrText: str
    ms: int


class AgentStepResponseReadValue(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tool: Literal['readValue']
    ref: str


class AgentStepResponseDone(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tool: Literal['done']
    value: str


class AgentStepResponseGiveUp(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tool: Literal['giveUp']
    reason: str


class AgentStepResponse(
    RootModel[
        AgentStepResponseClick
        | AgentStepResponseType
        | AgentStepResponsePress
        | AgentStepResponseWaitFor
        | AgentStepResponseReadValue
        | AgentStepResponseDone
        | AgentStepResponseGiveUp
    ]
):
    root: (
        AgentStepResponseClick
        | AgentStepResponseType
        | AgentStepResponsePress
        | AgentStepResponseWaitFor
        | AgentStepResponseReadValue
        | AgentStepResponseDone
        | AgentStepResponseGiveUp
    ) = Field(..., title='AgentStepResponse')
