# generated by datamodel-codegen:
#   filename:  citation-ref.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class CitationRef(BaseModel):
    """
    Server-side citation claim: item ids only, no pixel geometry.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    itemIds: list[str]
    quote: str
