# generated by datamodel-codegen:
#   filename:  citation.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, conint


class Box(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    x: float
    y: float
    w: float
    h: float


class Citation(BaseModel):
    """
    Client-side resolved citation: item ids turned into pixel boxes via DocumentSet.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    mergedPage: conint(ge=1)
    boxes: list[Box]
    quote: str
    sourceId: str
    sourcePage: conint(ge=1)
