# generated by datamodel-codegen:
#   filename:  document-source.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict


class Kind(StrEnum):
    emailBody = 'emailBody'
    attachment = 'attachment'
    upload = 'upload'


class DocumentSource(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sourceId: str
    kind: Kind
    name: str
    mime: str
