# generated by datamodel-codegen:
#   filename:  document-set.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from . import document_source_schema, manifest_entry_schema, page_schema


class SkippedItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    mime: str
    reason: str


class DocumentSet(BaseModel):
    """
    Client-side document set. mergedPdf bytes never cross the HTTPS boundary and are deliberately absent from this schema.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    setId: str
    sources: list[document_source_schema.DocumentSource] = Field(..., min_length=1)
    manifest: list[manifest_entry_schema.ManifestEntry]
    pages: list[page_schema.Page]
    skipped: list[SkippedItem] | None = None
