# generated by datamodel-codegen:
#   filename:  extracted-group.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from . import extracted_field_schema


class Row(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    cells: list[extracted_field_schema.ExtractedField]


class ExtractedGroup(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    groupId: str
    rows: list[Row]
