# generated by datamodel-codegen:
#   filename:  extraction-config.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class FieldDef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fieldId: str
    type: str
    description: str
    required: bool
    examples: list[str]
    enum: list[str] | None = None


class GroupDef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    groupId: str
    description: str
    fields: list[FieldDef]


class ExtractionConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    formId: str
    fields: list[FieldDef]
    groups: list[GroupDef]
