# generated by datamodel-codegen:
#   filename:  extraction-request.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, conint


class Item(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    text: str


class Page(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mergedPage: conint(ge=1)
    items: list[Item]


class Source(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    sourceId: str
    pages: list[Page]


class ExtractionRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    formId: str
    sources: list[Source]
