# generated by datamodel-codegen:
#   filename:  extracted-field.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, confloat

from . import citation_ref_schema


class Status(StrEnum):
    found = 'found'
    notFound = 'notFound'
    ambiguous = 'ambiguous'


class ExtractedField(BaseModel):
    """
    LLM structured-output boundary object: every property is required (nullable where absent), per OpenAI strict-schema mode.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    fieldId: str
    value: str | float | bool | None
    valueType: str
    status: Status
    confidence: confloat(ge=0.0, le=1.0)
    sourceId: str | None
    citations: list[citation_ref_schema.CitationRef]
    reason: str | None
