# generated by datamodel-codegen:
#   filename:  fill-event.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict


class Kind(StrEnum):
    stepStarted = 'stepStarted'
    stepVerified = 'stepVerified'
    stepRetrying = 'stepRetrying'
    stepFallback = 'stepFallback'
    stepFailed = 'stepFailed'
    stepSkipped = 'stepSkipped'


class FillEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    stepId: str
    kind: Kind
    attempt: int | None = None
    reason: str | None = None
