# generated by datamodel-codegen:
#   filename:  fill-report.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, ConfigDict


class Status(StrEnum):
    verified = 'verified'
    failed = 'failed'
    skipped = 'skipped'
    fallback = 'fallback'


class StepResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    stepId: str
    status: Status
    attempts: int
    reason: str | None = None


class FillReport(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    runId: str
    steps: list[StepResult]
    startedAt: AwareDatetime
    completedAt: AwareDatetime
