# generated by datamodel-codegen:
#   filename:  fill-plan.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from . import fill_step_schema


class FillPlan(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    steps: list[fill_step_schema.FillStep]
