# generated by datamodel-codegen:
#   filename:  fill-step.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict

from . import locator_spec_schema


class Kind(StrEnum):
    navigateTab = 'navigateTab'
    reveal = 'reveal'
    fillField = 'fillField'
    addRow = 'addRow'
    fillCell = 'fillCell'


class FillStep(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    stepId: str
    kind: Kind
    sectionId: str | None = None
    groupId: str | None = None
    fieldId: str | None = None
    colId: str | None = None
    rowIndex: int | None = None
    locator: locator_spec_schema.LocatorSpec | None = None
    value: str | None = None
