# generated by datamodel-codegen:
#   filename:  form-config.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Literal

from pydantic import BaseModel, ConfigDict

from . import locator_spec_schema


class Control(StrEnum):
    text = 'text'
    select = 'select'
    searchSelect = 'searchSelect'
    checkbox = 'checkbox'
    date = 'date'
    button = 'button'
    tab = 'tab'
    agGridCell = 'agGridCell'


class GridColumn(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fieldId: str
    colId: str
    control: str


class Tab(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    locator: locator_spec_schema.LocatorSpec


class RevealAction(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    action: Literal['click']
    locator: locator_spec_schema.LocatorSpec


class Field(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    fieldId: str
    control: Control
    locator: locator_spec_schema.LocatorSpec
    profile: str | None = None
    required: bool | None = None
    dependsOn: list[str] | None = None


class AddRow(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    locator: locator_spec_schema.LocatorSpec


class Grid(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    groupId: str
    control: Literal['agGrid']
    locator: locator_spec_schema.LocatorSpec
    addRow: AddRow | None = None
    columns: list[GridColumn]


class Section(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    tab: Tab | None = None
    reveal: list[RevealAction] | None = None
    fields: list[Field]
    grids: list[Grid]


class FormConfig(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    formId: str
    urlTemplate: str
    widgetProfiles: str
    sections: list[Section]
