# generated by datamodel-codegen:
#   filename:  locator-spec.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class Role(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    role: str


class LocatorSpec(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    formControlName: str | None = None
    label: str | None = None
    role: Role | None = None
    css: str | None = None
    within: LocatorSpec | None = None
    nth: int | None = None


LocatorSpec.model_rebuild()
