# generated by datamodel-codegen:
#   filename:  manifest-entry.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, conint


class ManifestEntry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mergedPage: conint(ge=1)
    sourceId: str
    sourcePage: conint(ge=1)
