# generated by datamodel-codegen:
#   filename:  match-option-request.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class MatchOptionRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    wanted: str
    options: list[str]
