# generated by datamodel-codegen:
#   filename:  match-option-response.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, confloat


class MatchOptionResponse(BaseModel):
    """
    LLM structured-output boundary object: every property is required.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    index: int | None
    confidence: confloat(ge=0.0, le=1.0)
    reason: str
