# generated by datamodel-codegen:
#   filename:  page.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, conint

from . import text_item_schema


class Page(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    mergedPage: conint(ge=1)
    width: float
    height: float
    items: list[text_item_schema.TextItem]
