# generated by datamodel-codegen:
#   filename:  resolved-field.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, confloat

from . import citation_schema


class Status(StrEnum):
    found = 'found'
    notFound = 'notFound'
    ambiguous = 'ambiguous'
    unverifiedCitation = 'unverifiedCitation'


class ResolvedField(BaseModel):
    """
    Standalone flat schema (deliberately not composed via allOf on ExtractedField, whose additionalProperties:false CitationRef items would conflict with Citation items in the same allOf).
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    fieldId: str
    value: str | float | bool | None
    valueType: str
    status: Status
    confidence: confloat(ge=0.0, le=1.0)
    sourceId: str | None
    reason: str | None
    citations: list[citation_schema.Citation]
