# generated by datamodel-codegen:
#   filename:  run-log-event.schema.json

from __future__ import annotations

from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field


class RunLogEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    runId: str
    ts: AwareDatetime
    user: str
    kind: str
    payload: dict[str, Any] = Field(
        ...,
        description='Deliberate exception to additionalProperties:false: shape varies per kind, no closed value set is documented.',
    )
