# generated by datamodel-codegen:
#   filename:  text-item.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class TextItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    text: str
    x: float
    y: float
    w: float
    h: float
