# generated by datamodel-codegen:
#   filename:  widget-profiles.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, RootModel

from . import locator_spec_schema


class WidgetProfile(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    trigger: locator_spec_schema.LocatorSpec | None = None
    searchInput: locator_spec_schema.LocatorSpec | None = None
    optionList: locator_spec_schema.LocatorSpec | None = None
    optionItem: locator_spec_schema.LocatorSpec | None = None
    loadingIndicator: locator_spec_schema.LocatorSpec | None = None
    selectedValue: locator_spec_schema.LocatorSpec | None = None
    settleMs: float | None = None
    maxWaitMs: float | None = None


class WidgetProfiles(RootModel[dict[str, WidgetProfile]]):
    """
    Map keyed by profile name. Deliberate exception to additionalProperties:false: the map's keys are dynamic profile names, but each value is closed.
    """

    root: dict[str, WidgetProfile]
